### ISSUE TITLE
Hours Wasted.

### ISSUE THREAD

**Issue by maxcramer** [jscomplete/rgs-star-match#1]
This app doesn't work. Please update and update your tutorial! I have cloned, copy and pasted your code and everything in between and all i get is 500 error. Please advise as currently this is fucked.

**Comment by RajwardhanShinde** [comment]
@maxcramer Did you find any solution i am suffering from same problem
@samerbuna Sir Please Look into this

**Comment by samerbuna** [comment]
Apologies for the troubles. The repo had some unnecessary complexities which I just removed. I've also upgraded all dependencies and code to the latest as of now.

Please try again and let me know.

**Comment by RajwardhanShinde** [comment]
@samerbuna Yes, Sir it works now. Can you guide what should be my next steps and what should be used as backend with react I know Django does that help?
